name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=runtime_binary::libphysx.clawed-linux-x86_64-$RELEASE_VERSION.so
      - run: echo "LLVM_INSTALL_PREFIX=${{ github.workspace }}/llvm" >> $GITHUB_ENV
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.LLVM_INSTALL_PREFIX }}
          key: llvm-9.0
      - name: Install LLVM And Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "9.0"
          directory: ${{ env.LLVM_INSTALL_PREFIX }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Build Binaries
        run: |
          cd ${{ github.workspace }}/src/lib/ && ./build.sh desktop
      - name: Rename Binaries
        run: >-
          mv src/lib/build/desktop/libphysx.clawed.so ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=runtime_binary::physx.clawed-windows-x64-$RELEASE_VERSION.dll
        shell: bash
      - name: Build Binaries
        run: |
          cd ${{ github.workspace }}/src/lib/
          ./build.ps1
      - name: Rename Binaries
        run: >-
          mv src/lib/build/desktop/physx.clawed.dll ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
  build-android:
    runs-on: windows-2019
    steps:
      - name: Check Out Everything
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup PhysX-compatible obsolete Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-physx-android-ndk
        with:
          ndk-version: r11c
          add-to-path: false
      - name: Setup Build Variables
        id: vars
        run: >-
          export RELEASE_VERSION=${GITHUB_REF#refs/*/} &&
          echo ::set-output name=ndk_version::22.1.7171670 &&
          echo ::set-output name=runtime_binary::libphysx.clawed-android-aarch64-$RELEASE_VERSION.so
        shell: bash
      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: |
            $ANDROID_HOME/ndk/${{ steps.vars.outputs.ndk_version }}/
          key: ndk-${{ steps.vars.outputs.runtime_binary }}
      - name: Setup Unix Paths
        run: |
          $ObsoleteNdkPath="${{ steps.setup-physx-android-ndk.outputs.ndk-path }}" -replace '\\','/'
          $WorkspacePath="${{ github.workspace }}" -replace '\\','/'
          echo "OBSOLETE_ANDROID_NDK=$ObsoleteNdkPath" >> $Env:GITHUB_ENV
          echo "WORKSPACE_PATH=$WorkspacePath" >> $Env:GITHUB_ENV
      - name: Install Required NDK version
        run: |
          cd $Env:ANDROID_HOME/tools/bin/
          ./sdkmanager --install "ndk;${{ steps.vars.outputs.ndk_version }}"
      - name: Build Binaries
        run: >-
          cd $WORKSPACE_PATH/src/lib/
          && ./build.sh --arch aarch64
          --physx-android-ndk $OBSOLETE_ANDROID_NDK
          --ndk $ANDROID_HOME/ndk/${{ steps.vars.outputs.ndk_version }}
          android
        shell: bash
      - name: Rename Binaries
        run: >-
          mv src/lib/build/android/libphysx.clawed.so ${{ steps.vars.outputs.runtime_binary }}
      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.vars.outputs.runtime_binary }}
